const KEY='lets-talk-project-v1';
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const defaults=()=>({name:"LET'S TALK",nodes:[{id:uid(),type:'dialogue',speaker:'小明',text:'你好，欢迎来到 LET\'S TALK。',speed:45,avatar:null,media:null},{id:uid(),type:'narration',speaker:'',text:'夜幕降临，新的故事即将开始。',speed:45,avatar:null,media:null}],floors:[{id:uid(),username:'楼主',content:'欢迎来到我的故事论坛。',image:null}],bgm:null,bgmLoop:true});
let project=load(),editingNode=null,editingFloor=null,current=0,shown=0,typeTimer=null,autoTimer=null,deferredPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||defaults()}catch{return defaults()}}
function save(){localStorage.setItem(KEY,JSON.stringify(project));renderAll()}
function esc(v=''){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
const label=t=>({dialogue:'人物对话',narration:'旁白',image:'图片',animation:'动画'}[t]);
function fileData(file){return new Promise((ok,no)=>{if(!file)return ok(null);const r=new FileReader();r.onload=()=>ok({name:file.name,type:file.type,data:r.result});r.onerror=no;r.readAsDataURL(file)})}
function renderAll(){renderNodes();renderFloors();$('#projectName').value=project.name;$('#bgmLoop').checked=project.bgmLoop;$('#bgmStatus').textContent=project.bgm?`已选择：${project.bgm.name}`:'未选择背景音乐'}
function renderNodes(){
 $('#nodeCount').textContent=`${project.nodes.length} 条内容`;
 $('#nodeList').innerHTML=project.nodes.map((n,i)=>`<article class="card" data-edit-node="${n.id}"><div class="card-head"><span class="badge">${i+1}</span><strong>${label(n.type)}${n.speaker?` · ${esc(n.speaker)}`:''}</strong><div class="mini-actions"><button data-up="${n.id}">↑</button><button data-down="${n.id}">↓</button><button data-delete-node="${n.id}">删</button></div></div>${n.text?`<p>${esc(n.text)}</p>`:''}${n.media?mediaHtml(n.media,'media-thumb'):''}</article>`).join('')||'<div class="empty">暂无剧情，使用下方按钮添加。</div>';
}
function mediaHtml(m,cls){return m.type.startsWith('video/')?`<video class="${cls}" src="${m.data}" controls></video>`:`<img class="${cls}" src="${m.data}" alt="剧情媒体" />`}
function renderFloors(){
 $('#floorCount').textContent=`${project.floors.length} 个楼层`;
 $('#floorList').innerHTML=project.floors.map((f,i)=>`<article class="card" data-edit-floor="${f.id}"><div class="card-head"><span class="badge">${i+1}楼</span><strong>${esc(f.username)}</strong><div class="mini-actions"><button data-delete-floor="${f.id}">删除</button></div></div><p>${esc(f.content)}</p>${f.image?`<img class="media-thumb" src="${f.image.data}" alt="帖子图片" />`:''}</article>`).join('')||'<div class="empty">暂无楼层。</div>';
}
function openNode(n){editingNode=n.id;$('#nodeId').value=n.id;$('#nodeDialogTitle').textContent=`编辑${label(n.type)}`;$('#speakerInput').value=n.speaker||'';$('#textInput').value=n.text||'';$('#speedInput').value=n.speed||45;$('#speedValue').textContent=n.speed||45;const media=['image','animation'].includes(n.type);$('#speakerField').classList.toggle('hidden',n.type!=='dialogue');$('#avatarField').classList.toggle('hidden',n.type!=='dialogue');$('#textField').classList.toggle('hidden',media);$('#speedField').classList.toggle('hidden',media);$('#mediaField').classList.toggle('hidden',!media);$('#nodeDialog').showModal()}
function openFloor(f){editingFloor=f.id;$('#floorId').value=f.id;$('#usernameInput').value=f.username;$('#contentInput').value=f.content;$('#floorDialog').showModal()}
function moveNode(id,delta){const i=project.nodes.findIndex(n=>n.id===id),j=i+delta;if(i<0||j<0||j>=project.nodes.length)return;[project.nodes[i],project.nodes[j]]=[project.nodes[j],project.nodes[i]];save()}
function showPage(name){$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='player'){current=Math.min(current,Math.max(0,project.nodes.length-1));startNode()}else stopPlayback()}
function stopPlayback(){clearInterval(typeTimer);clearTimeout(autoTimer);typeTimer=autoTimer=null;pauseBgm()}
function startNode(){stopPlayback();const n=project.nodes[current];$('#playerProgress').textContent=project.nodes.length?`${current+1} / ${project.nodes.length}`:'0 / 0';if(!n){$('#stage').innerHTML='<div class="empty">请先添加剧情内容</div>';return}shown=0;if(['image','animation'].includes(n.type)){renderStage(n);scheduleAuto(2200)}else{renderStage(n);typeTimer=setInterval(()=>{shown++;renderStage(n);if(shown>=n.text.length){clearInterval(typeTimer);scheduleAuto(1200)}},n.speed||45)}playBgm()}
function renderStage(n){if(['image','animation'].includes(n.type)){ $('#stage').innerHTML=n.media?mediaHtml(n.media,'scene-media'):`<div class="empty">尚未选择${label(n.type)}文件</div>`;return }const avatar=n.avatar?`<img class="avatar" src="${n.avatar.data}" alt="${esc(n.speaker)}头像"/>`:`<span class="avatar" style="display:grid;place-items:center">${esc((n.speaker||'?')[0])}</span>`;$('#stage').innerHTML=n.type==='narration'?`<div class="narration">${esc(n.text.slice(0,shown))}</div>`:`<div class="dialogue-panel"><div class="speaker">${avatar}<span>${esc(n.speaker||'未命名角色')}</span></div><div class="bubble">${esc(n.text.slice(0,shown))}</div></div>`}
function scheduleAuto(ms){clearTimeout(autoTimer);if($('#autoPlay').checked)autoTimer=setTimeout(next,ms)}
function next(){if(current<project.nodes.length-1){current++;startNode()}else{$('#autoPlay').checked=false;pauseBgm()}}
function action(){const n=project.nodes[current];if(!n)return;if(!['image','animation'].includes(n.type)&&shown<n.text.length){shown=n.text.length;clearInterval(typeTimer);renderStage(n);scheduleAuto(1200)}else next()}
let audio=null;function playBgm(){if(!project.bgm)return;if(!audio||audio.src!==project.bgm.data){audio=new Audio(project.bgm.data);audio.loop=project.bgmLoop}audio.play().catch(()=>{})}function pauseBgm(){if(audio)audio.pause()}
$$('.tabs button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$$('[data-add-node]').forEach(b=>b.onclick=()=>{const type=b.dataset.addNode,n={id:uid(),type,speaker:type==='dialogue'?'新角色':'',text:['image','animation'].includes(type)?'':'请输入内容',speed:45,avatar:null,media:null};project.nodes.push(n);save();openNode(n)});
$('#nodeList').onclick=e=>{const del=e.target.closest('[data-delete-node]'),up=e.target.closest('[data-up]'),down=e.target.closest('[data-down]');if(del){e.stopPropagation();project.nodes=project.nodes.filter(n=>n.id!==del.dataset.deleteNode);save()}else if(up){e.stopPropagation();moveNode(up.dataset.up,-1)}else if(down){e.stopPropagation();moveNode(down.dataset.down,1)}else{const c=e.target.closest('[data-edit-node]');if(c)openNode(project.nodes.find(n=>n.id===c.dataset.editNode))}};
$('#speedInput').oninput=e=>$('#speedValue').textContent=e.target.value;
$('#saveNode').onclick=async e=>{e.preventDefault();const n=project.nodes.find(x=>x.id===editingNode);if(!n)return;const av=$('#avatarInput').files[0],media=$('#mediaInput').files[0];n.speaker=$('#speakerInput').value.trim();n.text=$('#textInput').value;n.speed=Number($('#speedInput').value);if(av)n.avatar=await fileData(av);if(media)n.media=await fileData(media);save();$('#nodeForm').reset();$('#nodeDialog').close();toast('节点已保存')};
$('#addFloor').onclick=()=>{const f={id:uid(),username:'新用户',content:'请输入楼层内容',image:null};project.floors.push(f);save();openFloor(f)};
$('#floorList').onclick=e=>{const d=e.target.closest('[data-delete-floor]');if(d){e.stopPropagation();project.floors=project.floors.filter(f=>f.id!==d.dataset.deleteFloor);save()}else{const c=e.target.closest('[data-edit-floor]');if(c)openFloor(project.floors.find(f=>f.id===c.dataset.editFloor))}};
$('#saveFloor').onclick=async e=>{e.preventDefault();const f=project.floors.find(x=>x.id===editingFloor);if(!f)return;f.username=$('#usernameInput').value.trim();f.content=$('#contentInput').value;const image=$('#floorImageInput').files[0];if(image)f.image=await fileData(image);save();$('#floorForm').reset();$('#floorDialog').close();toast('楼层已保存')};
$('#txtInput').onchange=async e=>{const text=await e.target.files[0]?.text();if(!text)return;const added=text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(line=>{const m=line.match(/^([^：:]+)[：:]\s*(.+)$/);if(!m)return null;return{id:uid(),type:/^(旁白|narration)$/i.test(m[1].trim())?'narration':'dialogue',speaker:/^(旁白|narration)$/i.test(m[1].trim())?'':m[1].trim(),text:m[2],speed:45,avatar:null,media:null}}).filter(Boolean);project.nodes.push(...added);save();toast(`已导入 ${added.length} 条`);e.target.value=''};
$('#projectName').onchange=e=>{project.name=e.target.value.trim()||"LET'S TALK";save()};$('#bgmLoop').onchange=e=>{project.bgmLoop=e.target.checked;if(audio)audio.loop=e.target.checked;save()};$('#bgmInput').onchange=async e=>{project.bgm=await fileData(e.target.files[0]);save();toast('背景音乐已保存')};
$('#prevNode').onclick=()=>{if(current>0){current--;startNode()}};$('#nextNode').onclick=next;$('#playAction').onclick=action;$('#autoPlay').onchange=()=>startNode();
$('#exportProject').onclick=()=>{const blob=new Blob([JSON.stringify(project)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${project.name.replace(/[^\w\u4e00-\u9fa5-]+/g,'_')}.letstalk`;a.click();URL.revokeObjectURL(a.href)};
$('#importProject').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.nodes)||!Array.isArray(data.floors))throw Error('格式错误');project=data;save();toast('项目导入成功')}catch(err){toast(`导入失败：${err.message}`)}e.target.value=''};
$('#resetProject').onclick=()=>{if(confirm('确定清空当前项目吗？此操作不能撤销。')){project=defaults();save();toast('项目已重置')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});async function install(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else alert('Android：浏览器菜单 → 安装应用/添加到主屏幕\niPhone：Safari 分享 → 添加到主屏幕')}$('#installBtn').onclick=install;$('#installBtn2').onclick=install;
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderAll();
